# Generated by Django 5.0.2 on 2024-11-05 08:10

import auth_system.custom_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraccount_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=auth_system.custom_storage.MediaStorage(), upload_to=''),
        ),
    ]
